# Generated by Django 5.2.1 on 2026-07-04 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('balance', models.BigIntegerField(default=1000)),
                ('coins_purchased', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=120)),
                ('skin_name', models.CharField(max_length=180)),
                ('skin_image', models.CharField(blank=True, max_length=400)),
                ('skin_price', models.BigIntegerField(default=0)),
                ('rarity', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('wear', models.CharField(blank=True, max_length=40)),
                ('sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.case')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='api.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
