# Generated by Django 5.2.1 on 2026-07-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_openrecord_coinpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='daily_claimed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='daily_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='invited_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_won',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.BigIntegerField(default=1500),
        ),
    ]
